# Generated by Django 2.2.6 on 2019-11-24 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 12, 53, 28, 578951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 12, 53, 28, 578951, tzinfo=utc)),
        ),
    ]
